services:
  voicevox-cpu:
    profiles: [voicevox-cpu]
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - '127.0.0.1:50021:50021'
    restart: on-failure
  voicevox-gpu:
    profiles: [voicevox-gpu]
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    ports:
      - '127.0.0.1:50021:50021'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: on-failure
  piper:
    profiles: [piper]
    image: ghcr.io/arunk140/serve-piper-tts:latest
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - ./models:/go/src/app/models
    restart: on-failure
  libretranslate:
    image: michaelf34/libretranslate:1.3.11
    ports:
      - '127.0.0.1:5000:5000'
    restart: on-failure
